{
 "title": "WebLogic Server Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domainName",
    "label": "Domain",
    "query": "label_values(weblogic_domainUID)"
   },
   {
    "name": "clusterName",
    "label": "Cluster",
    "query": "label_values(wls_jvm_uptime{weblogic_domainUID=\"$domainName\"},weblogic_clusterName)"
   },
   {
    "name": "serverName",
    "label": "Server",
    "query": "label_values(wls_jvm_uptime{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"},weblogic_serverName)"
   },
   { "name": "topN", "label": "Top N", "query": "3, 5, 7, 10" }
  ]
 },
 "panels": [
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Servers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count (wls_jvm_uptime{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (name))",
     "legendFormat": "{{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Server Name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "repeat": "serverName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "wls_server_activation_time{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\",weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 1 },
   "repeat": "serverName",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wls_server_state_val{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 1 },
   "repeat": "serverName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - wls_jvm_heap_free_percent{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Running Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 1 },
   "repeat": "serverName",
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "wls_jvm_uptime{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Open Sockets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "repeat": "serverName",
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "wls_server_open_sockets_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Deployed Applications",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(wls_webapp_config_deployment_state{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"}) by (app))"
    }
   ]
  },
  {
   "title": "Server Name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "wls_server_activation_time{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\",weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Server Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wls_server_state_val{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - wls_jvm_heap_free_percent{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Running Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 4 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "wls_jvm_uptime{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "Open Sockets",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "wls_server_open_sockets_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=\"$serverName\"}"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "wls_jvm_heap_free_current{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": " Heap Free  ({{weblogic_serverName}})"
    },
    {
     "expr": "wls_jvm_heap_size_current{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "Heap Size ({{weblogic_serverName}})"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "wls_jvm_process_cpu_load{weblogic_domainUID=~\"$domainName\", weblogic_clusterName=~\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"} * 100",
     "legendFormat": " {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wls_threadpool_execute_thread_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "Total Threads ({{weblogic_serverName}})"
    },
    {
     "expr": "wls_threadpool_stuck_thread_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "Stuck Threads ({{weblogic_serverName}})"
    }
   ]
  },
  { "title": "Web Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Total Sessions (top $topN)",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "topk($topN,sum(wls_webapp_config_sessions_opened_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (app))"
    }
   ]
  },
  {
   "title": "Total Requests (top $topN)",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "topk($topN,sum(wls_servlet_invocation_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (app))"
    }
   ]
  },
  {
   "title": "Total Execution Time (top $topN)",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "topk($topN,sum(wls_servlet_execution_time_total{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (app))"
    }
   ]
  },
  {
   "title": "Current Sessions ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(wls_webapp_config_open_sessions_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (app)",
     "legendFormat": "{{app}}"
    },
    {}
   ]
  },
  {
   "title": "Session Rate ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": " sum(irate(wls_webapp_config_sessions_opened_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[1m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Execution Time per Request ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(wls_servlet_execution_time_average{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (app)) / (count(wls_servlet_execution_time_average{weblogic_domainUID=\"domain1\", weblogic_clusterName=\"cluster-1\"}) by (app))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Request Rate ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(wls_servlet_invocation_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[1m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Data Sources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(wls_datasource_leaked_connection_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (weblogic_serverName,name)"
    },
    {
     "expr": "sum(wls_datasource_curr_capacity{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (weblogic_serverName,name)"
    },
    {
     "expr": "sum(wls_datasource_failed_reserve_request_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (weblogic_serverName,name)"
    },
    {
     "expr": "sum(wls_datasource_connections_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (weblogic_serverName,name)"
    },
    {
     "expr": "(wls_datasource_active_connections_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"} / (wls_datasource_active_connections_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"} + wls_datasource_curr_capacity{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\"})) * 100"
    }
   ]
  },
  {
   "title": "Pending Connection Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wls_datasource_waiting_for_connection_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": " {{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Average Connection Delay Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "wls_datasource_connection_delay_time{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": " {{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Connection Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "irate(wls_datasource_connections_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[1m])",
     "legendFormat": " {{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wls_datasource_active_connections_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": " {{name}} @ {{weblogic_serverName}}"
    }
   ]
  },
  { "title": "JMS Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum(wls_jms_destinations_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)"
    },
    {
     "expr": "sum(wls_jms_session_pools_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)"
    },
    {
     "expr": "sum(wls_jms_messages_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)"
    },
    {
     "expr": "sum(wls_jms_bytes_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)"
    },
    {
     "expr": "sum(wls_jms_destinations_total_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)"
    },
    {
     "expr": "sum(wls_jms_destinations_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (jmsserver)"
    }
   ]
  },
  {
   "title": "Session Pools",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wls_jms_session_pools_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "{{jmsserver}}"
    }
   ]
  },
  {
   "title": "Received Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "wls_jms_messages_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "Current ({{jmsserver}})"
    },
    {
     "expr": "wls_jms_messages_pending_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "Pending ({{jmsserver}})"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "wls_jms_bytes_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "Current ({{jmsserver}})"
    },
    {
     "expr": "wls_jms_bytes_pending_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}",
     "legendFormat": "Pending ({{jmsserver}})"
    }
   ]
  },
  {
   "title": "Message Rate ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "irate(wls_jms_messages_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[1m])",
     "legendFormat": "{{jmsserver}}"
    }
   ]
  },
  {
   "title": "Bytes Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "irate(wls_jms_bytes_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}[1m])",
     "legendFormat": "{{jmsserver}}"
    }
   ]
  },
  {
   "title": "Destinations Overview",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(wls_jms_dest_consumers_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (destination)"
    },
    {
     "expr": "sum(wls_jms_dest_messages_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (destination)"
    },
    {
     "expr": "sum(wls_jms_dest_messages_pending_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (destination)"
    },
    {
     "expr": "sum(wls_jms_dest_bytes_current_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (destination)"
    },
    {
     "expr": "sum(wls_jms_dest_bytes_pending_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (destination)"
    },
    {
     "expr": "sum(wls_jms_dest_messages_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (destination)"
    },
    {
     "expr": "sum(wls_jms_dest_bytes_received_count{weblogic_domainUID=\"$domainName\", weblogic_clusterName=\"$clusterName\", weblogic_serverName=~\"${serverName:regex}\"}) by (destination)"
    }
   ]
  }
 ]
}